name: build

on:
  workflow_run:
    workflows:
      - lint
      - tests
    types:
      - completed
  push:
    branches:
      - new-build-strategy
  pull_request:
    branches:
      - new-build-strategy

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      # Install Tools
      - name: Install Tools
        run: |
          sudo add-apt-repository -y ppa:openjdk-r/ppa
          sudo apt update
          sudo apt install -y wget build-essential python3 python3-pip \
            verilator libevent-dev libjson-c-dev device-tree-compiler \
            python3-setuptools python3-requests python3-pexpect \
            python3-colorama python3-serial python3-packaging python3-yaml \
            ninja-build curl apt-transport-https gnupg openjdk-8-jdk -y \
            libxcb cairo
          sudo update-alternatives --config java
          sudo update-alternatives --config javac
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo -H gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
          sudo chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
          sudo apt update
          sudo apt -y install sbt
          pip3 install -r requirements.txt
          pip3 install --upgrade build

      # Install (n)Migen / LiteX / Cores
      - name: Install LiteX
        run: |
          wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
          python3 litex_setup.py init install --user

      # Install RISC-V GCC
      - name: Install RISC-V GCC
        run: |
          wget https://static.dev.sifive.com/dev-tools/freedom-tools/v2020.12/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
          tar -xf $PWD/riscv64-*.tar.gz
          sudo mkdir /usr/local/riscv
          sudo cp -r $PWD/riscv64-*/* /usr/local/riscv

      # Build Cores Package
      - name: Build cores package
        run: |
          cd ${{ github.workspace }}/core_package 
          python3 -m build
          pip install dist/*.whl

      # Build SoC Package
      - name: Build soc package
        run: |
          cd ${{ github.workspace }}/soc_package
          python3 -m build
          pip install dist/*.whl
      
      # Build SoC
      - name: Build SoC
        run: |
          cd ${{ github.workspace }}/linux-on-litex-vexriscv
          python3 make.py --board orange_crab_ctkey --device 85F --doc --build

      # Build linux
      - name: Checkout Buildroot 2024.02.10
        uses: actions/checkout@v4
        with:
          repository: https://gitlab.com/buildroot.org/buildroot.git
          ref: 2024.02.x
          path: ${{ github.workspace }}/buildroot

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y which sed make binutils build-essential gcc g++ diffutils bash patch gzip bzip2 perl tar cpio python unzip rsync file bc wget git rsync bc python3 findutils

      - name: Build linux
        run: |
          cd ${{ github.workspace }}/buildroot
          make BR2_EXTERNAL=../linux-on-litex-vexriscv/buildroot/ litex_vexriscv_defconfig
          make

      # Store artifacts
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soc-build
          path: |
            ${{ github.workspace }}/linux-on-litex-vexriscv/images
            ${{ github.workspace }}/soc_package/dist/*.whl
            ${{ github.workspace }}/core_package/dist/*.whl
          if-no-files-found: error


