name: build

on:
  workflow_run:
    workflows:
      - lint
      - tests
    types:
      - completed
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Build development environment
        run: docker buildx build -t local $PWD/.devcontainer
      - name: Build SoC
        run: docker run -v $PWD:/srv -w /srv -u 1000 local python3 ./soc.py --build

