name: tests

on:
  workflow_run:
    workflows:
      - lint
    types:
      - completed
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [flake8, pylint, ruff, mypy, pyright, fixit]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Download Litex
        run: wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
      - name: Install Litex
        run: python3 litex_setup.py --init --install --config=standard
      - uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: ${{ matrix.linter }}
          python-version: 3.12